spring.application.name=service-registry
server.port=8761

# Eureka Server config
eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false

# Docker hostname (good practice)
eureka.instance.hostname=service-registry

# Better container networking
eureka.instance.prefer-ip-address=true